---
title: "HIP: Brief Pain Inventory"
subtitle: "Factor analysis"
author: "Peter Kamerman, Tory Madden"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: 
    html_document:
        theme: yeti
        keep_md: true
        highlight: pygments
        toc: true
        toc_float: true
        code_folding: show
---

```{r setup, include = FALSE}
# Load packages
library(tidyverse)
library(magrittr)
library(psych)
library(corrr)
library(skimr)

# Set knitr options
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      fig.retina = 2,
                      fig.align = 'center',
                      fig.path = 'figures/bdi-factor-analysis/',
                      fig.width = 7,
                      fig.height = 7)
```

----

A factor analysis of the pain intensity and pain inteference components of the Brief Pain Inventory (BPI). Only data recorded at the baseline (time = 0) was used, and only datasets with complete cases were used (i.e., data from _R1_ is excluded because average pain data were not collected). 

----

# Import data

```{r import_data}
# Get data
bpi_fac <- read_rds('./data/bpi_factor_analysis.rds')
```

----

# Clean data

```{r clean}
# Fix column names
names(bpi_fac) <- c('Worst pain', 'Least pain', 'Average pain', 'Pain now',
                    'Activities of daily living', 'Mood', 'Walking', 'Work', 
                    'Relationship with other', 'Sleep', 'Enjoyment of life')
```

----

# Quick look

```{r quick_look}
glimpse(bpi_fac)
head(bpi_fac)
tail(bpi_fac)
skim(bpi_fac)
```

----

# Factor analysis

### Scree plot

```{r factor_analysis}
# Scree plot to check whether 2-factor solution is optimal
# Use Pearson's correlation (ordinal data, but enough levels to treat as continuous)
# and maximum likelihood ('ml') factoring method ('minres' gives warnings)
fa.parallel(x = cor(bpi_fac,
                    method = 'pearson'),
            n.obs = 105,
            fm = 'ml',
            fa = 'fa')
```

### Factor structure

```{r factor_analysis2}
# Factor analysis with 2-factor solution
(bpi_fa <- fa(r = cor(bpi_fac,
                      method = 'pearson'),
             nfactors = 2,
             n.obs = 105,
             fm = 'ml',
             rotate = 'varimax'))

# Plot
fa.plot(bpi_fa,
        labels = names(bpi_fac),
        xlim = c(-0.1, 1),
        ylim = c(-0.1, 1),
        xlab = 'MR1: Pain interference',
        ylab = 'MR2: Pain intensity')
```

----

# Internal consistency

### Correlation matrix

```{r internal_consistency}
# Correlation matrix
correlate(bpi_fac) %>% 
    rearrange() %>% 
    shave() 

# Network plot of correlaton matrix
correlate(bpi_fac) %>%
    network_plot(legend = TRUE,
                 colors = c('red', 'white', 'blue'))
```

### Cronbach alpha and drop 1 analysis

```{r internal_consistency2}
# Generate alpha and drop-1 summary
alpha(bpi_fac)
```

----

# Summary

The scree plot indicates that a two-factor structure is optimal, and a confirmatory two-factor factor analysis indicates partitioning of items onto pain interference and pain intensity factors. 

The internal consistency is good, and does not show major changes when dropping individual items.

----

# Session information

```{r session_info, echo = FALSE}
sessionInfo()
```