---
title: "HIP: Demographic data table for the manuscript"
author: "Peter Kamerman and Tory Madden"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: html_document
---

```{r setup, include = FALSE}
# Load packages
library(tidyverse)
library(skimr)
library(magrittr)

# Set knitr options
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE)
```

----

Basic descriptive statistics of core demographic data at baseline (time = 0 weeks) for males, females, and the whole cohort. 

----

# Import data

```{r import_data}
# Get data
demo <- read_rds('./data/demographics.rds') %>%
    # Transfer CD4 data to CD4_recent if missing CD4_recent data (i.e. most updated CD4 count available)
    mutate(CD4_uptodate =
                     ifelse(is.na(CD4_recent),
                 CD4,
                 CD4_recent)) %>%
    # Categorise years of schooling into 7 years or less, 8-12 years, and more than 12 years of education
    mutate(Education_category = case_when(
        Years_education <= 7 ~ "0-7 years",
        Years_education > 7 & Years_education <= 12 ~ "8-12 years",
        Years_education > 12 ~ "More than 12 years")) %>%
    # Select required columns
    select(ID,
           Site,
           Sex,
           Age,
           Years_on_ART,
           CD4_uptodate,
           HIV_mx,
           Education_category,
           SOS_mnemonic)

demo %<>% mutate(HIV_mx = case_when(
    HIV_mx == "first-line" ~ "first-line ART",
    HIV_mx == "second-line" ~ "second-line ART",
    HIV_mx == "monitoring" ~ "no ART")) 

demo %<>% mutate(HIV_mx = factor(HIV_mx, levels = c("first-line ART", "second-line ART", "no ART")))

# Read in other outcomes info
bdi <- read_rds('./data/bdi.rds') %>%
    mutate(ID = stringr::str_to_upper(ID)) %>%
    select(ID,
           ends_with("BL"))  %>%
    # Make a total score column
    mutate_at(.vars = 2:22, as.numeric) %>%
    mutate(bdi_BL = rowSums(.[2:22], na.rm = TRUE),
           # Treat BDI as a discrete scale
           bdi_BL = as.integer(round(bdi_BL))) %>%
    select(ID,
           bdi_BL)

bpi <- read_rds('./data/bpi.rds') %>%
    mutate(ID = stringr::str_to_upper(ID)) %>%
    select(ID,
           ends_with("BL")) %>%
    # Select columns
    select(ID, 
           3:6,
           9:15) %>%
    # Calculate PSS at baseline
    mutate(PSS_BL = rowMeans(.[2:5], na.rm = TRUE),
           # Treat PSS as a discrete scale
           PSS_BL = as.integer(round(PSS_BL))) %>%
    # Calculate PIS at baseline
    mutate(PIS_BL = rowMeans(.[6:12], na.rm = TRUE),
           # Treat PIS as a discrete scale
           PIS_BL = as.integer(round(PIS_BL))) %>%
    #remove unwanted columns
    select(ID,
           PSS_BL,
           PIS_BL)


# EQ5D

eq5d <- read_rds('./data/eq5d.rds') %>%
    mutate(ID = stringr::str_to_upper(ID)) %>%
    select(ID,
           contains("BL"))

# Calculate eq5d index score for each time point
# Create basic term = 1 for all cases in new column
eq5d$index_core <- 1

# Sum all rows for total BL index score and allocate to a new column in eq5d data frame 
eq5d %<>% mutate(BL_index_sum = rowSums(.[2:6], na.rm = TRUE))

# Create constant term to subtract if any domain scores > 1 (i.e. sum > 5)
eq5d %<>% mutate(EQ5D_constant_BL = ifelse(BL_index_sum > 5, 
                                        yes = 0.081, 
                                        no = 0))

# 1. Create variable for subtraction for each domain and time point: 
# Call it (for example) BL_Mobility_index
# Use values from table in an ifelse statement
# THEN
# 2. Compute the index score for each time point using: 
# BL_index_score = index_core - constant_index - BL_Mobility_index - (etc - for each domain).

# Baseline #
############
eq5d %<>% mutate(BL_Mobility_index = ifelse(Mobility.BL == 2, 
                                                   yes = 0.069,
                                                   no = ifelse(Mobility.BL == 3, 
                                                               yes = 0.314,
                                                               no = 0)))

eq5d <- eq5d %>% mutate(BL_Self_care_index = ifelse(Self_care.BL == 2, 
                                                   yes = 0.104,
                                                   no = ifelse(Self_care.BL == 3, 
                                                               yes = 0.214,
                                                               no = 0)))

eq5d <- eq5d %>% mutate(BL_Usual_act_index = ifelse(Usual_activities.BL == 2, 
                                                  yes = 0.036,
                                                  no = ifelse(Usual_activities.BL == 3, 
                                                              yes = 0.094,
                                                              no = 0)))

eq5d <- eq5d %>% mutate(BL_EQ_Pain_index = ifelse(Pain.BL == 2, 
                                                    yes = 0.123,
                                                    no = ifelse(Pain.BL == 3, 
                                                                yes = 0.386,
                                                                no = 0)))

eq5d <- eq5d %>% mutate(BL_Anx_depr_index = ifelse(Anxiety_and_depression.BL == 2, 
                                                    yes = 0.071,
                                                    no = ifelse(Anxiety_and_depression.BL == 3, 
                                                                yes = 0.236,
                                                                no = 0)))

# Index score
eq5d %<>% mutate(eq5d_index_BL = index_core - EQ5D_constant_BL - BL_Mobility_index - BL_Self_care_index - BL_Usual_act_index - BL_EQ_Pain_index - BL_Anx_depr_index)

eq5d %<>% select(ID,
                 State_of_health.BL,
                 eq5d_index_BL)

se6 <- read_rds('./data/se6.rds') %>%
    mutate(ID = stringr::str_to_upper(ID)) %>%
    select(ID,
           ends_with("BL")) %>%
    # Calculate SE6 at baseline
    mutate(se6_BL = rowMeans(.[2:7], na.rm = TRUE),
           # Treat SE6 as a discrete scale
           se6_BL = as.integer(round(se6_BL))) %>%
    #remove unwanted columns
    select(ID,
           se6_BL)

# Bind all together

Baseline <- left_join(demo, bdi) %>%
    left_join(bpi) %>%
    left_join(eq5d) %>%
    left_join(se6)

```

----

# Quick look

```{r quick_look}
glimpse(Baseline)
Baseline %>% 
    skim_to_wide() %>% 
    select(variable, missing, complete, n) %>%
    mutate_at(.vars = c(2:4),
              .funs = as.numeric) %>% 
    arrange(complete) %>% 
    kable(caption = 'Tabular summary of data completeness')
```

----

# Sample size

```{r sample_size, results = 'asis'}
# Rename a few columns
library(data.table)

Baseline %<>% select(ID,
                     Age,
                     Sex,
                     Education_category,
                     SOS_mnemonic,
                     Years_on_ART,
                     HIV_mx,
                     CD4_uptodate,
                     PSS_BL,
                     PIS_BL,
                     bdi_BL,
                     se6_BL,
                     State_of_health.BL,
                     eq5d_index_BL)

# Set variable labels for use in the table using labelled:var_label command

library(labelled)

# Load package
library(tableone)

# Create a list of the variables we want in Table 1

listVars <- c("Age", "Site", "Education_category", "SOS_mnemonic", "Years_on_ART", "HIV_mx", "CD4_uptodate", "PSS_BL", "PIS_BL", "bdi_BL", "se6_BL", "State_of_health.BL", "eq5d_index_BL")

#listVars <- c("Age", "Site", "CD4_uptodate", "HIV_mx", "Education_category", "SOS_mnemonic")

# Define categorical variables
catVars <- c("Site", "HIV_mx", "Education_category", "SOS_mnemonic", "Sex")

#catVars <- c("Site","HIV_mx","Education_category", "SOS_mnemonic", "Sex")

# Create Table 1
table1 <- CreateTableOne(listVars, Baseline, catVars, strata = c("Sex"))
table1

summary(table1)

# Specify CD4 count must be treated as non-normal
biomarker <- "CD4_uptodate"

var_label(Baseline) <- list(
    Education_category = "Education category", 
    SOS_mnemonic = "SOS mnemonic",
    Years_on_ART = "Years on ART",
    HIV_mx = "HIV treatment", 
    CD4_uptodate = "Most recent CD4 count",
    PSS_BL = "Pain severity (PSS)", 
    PIS_BL = "Pain interference (PIS)",
    bdi_BL = "Depression (BDI)", 
    se6_BL = "Self-efficacy (SE-6)",
    State_of_health.BL = "HRQOL (EQ5D VAS)", 
    eq5d_index_BL = "HRQOL (EQ5D index)")

print(table1, nonnormal = biomarker, varLabels = TRUE)

# Save output to txt

tab1Mat <- print(table1, nonnormal = biomarker, quote = FALSE, noSpaces = TRUE, printToggle = FALSE, varLabels = TRUE)
## Save to a CSV file
write.csv(tab1Mat, file = "myTable1.csv")

read.csv("myTable1.csv")
library(ztable)
options(ztable.type="pdf")
z <- ztable(tab1Mat, align="ccccc")

rgroup <- c("", "Demographics","HIV management","Study outcomes")
n.rgroup  <- c(1, 6 , 6, 6)
z <- addrgroup(z,rgroup=rgroup,n.rgroup=n.rgroup,cspan.rgroup=1)
print(z)

```



----

# Session information

```{r session_info, echo = FALSE}
sessionInfo()
```