---
title: "HIP demographics: Descriptive analyses"
author: "Peter Kamerman and Tory Madden"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: 
    html_document:
        theme: yeti
        keep_md: true
        highlight: pygments
        df_print: paged
        toc: true
        toc_float: true
        code_folding: show
---

```{r setup, include = FALSE}
# Load packages
library(tidyverse)
library(skimr)

# Set ggplot2 theme
theme_set(new = theme_bw(base_size = 14))

# Set knitr options
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      fig.retina = 2,
                      fig.align = 'center',
                      fig.path = 'figures/descriptive-demographics/',
                      fig.width = 7,
                      fig.height = 7)
```

----

# Import data

```{r import_data}
# Get data
demo <- read_rds('./data/demographics.rds')
```

----

# Quick look

```{r quick_look}
glimpse(demo)
head(demo)
tail(demo)
skim(demo)
```

----

# Sample size

```{r sample_size}
# Sample size by study site
demo %>%
    group_by(Site) %>%
    summarise(count = n()) %>%
    knitr::kable(., 
                 caption = 'Sample size by study site', 
                 col.names = c('Site', 'Count'))

# Sample size by study site and intervention group
demo %>%
    group_by(Site, Group) %>%
    summarise(count = n()) %>%
    group_by(Site) %>%
    mutate(percent = round(count / sum(count) * 100, 1)) %>%
    knitr::kable(., 
                 caption = 'Sample size by intervention group at each study site',
                 col.names = c('Site', 'Group', 'Count', 
                               'Percent (by site)'))
```

----

# Sex

```{r sex, fig.height = 5}
# Sex by study site
demo %>%
    group_by(Site, Sex) %>%
    summarise(count = sum(!is.na(Sex)),
              missing = sum(is.na(Sex))) %>%
    group_by(Site) %>%
    mutate(percent = round(count / sum(count) * 100, 1)) %>%
    knitr::kable(., 
                 caption = 'Self-identified sex by study site',
                 col.names = c('Site', 'Sex', 'Count', 'Missing', 
                               'Percent (by site)'))

# Plot 
ggplot(data = demo) +
    aes(x = Site,
        fill = Sex) +
    geom_bar(position = position_fill()) +
    labs(title = 'Participant sex (self-identified)',
         subtitle = 'Conditioned on study site',
         y = 'Proportion',
         x = 'Study site') +
    scale_fill_brewer(name = 'Sex: ',
                      type = 'qual',
                      palette = 'Dark2') +
    theme(legend.position = 'top')

# Sex by study site and intervention group
demo %>%
    group_by(Site, Group, Sex) %>%
    summarise(count = sum(!is.na(Sex)),
              missing = sum(is.na(Sex))) %>%
    group_by(Site) %>%
    mutate(sum = sum(count)) %>%
    mutate(percent = round(count / sum(count) * 100, 1)) %>%
    select(-sum) %>%
    knitr::kable(., 
                 caption = 'Self-identified sex by intervention group at each study site',
                 col.names = c('Site', 'Group', 'Sex', 'Count', 
                               'Missing', 'Percent (by site)'))

# Plot 
ggplot(data = demo) +
    aes(x = Group,
        fill = Sex) +
    geom_bar(position = position_fill()) +
    labs(title = 'Participant sex (self-identified)',
         subtitle = 'Conditioned on intervention group and study site',
         y = 'Proportion',
         x = 'Intervention group') +
    scale_fill_brewer(name = 'Sex: ',
                      type = 'qual',
                      palette = 'Dark2') +
    facet_wrap(~ Site, 
               ncol = 4, 
               labeller = label_both) +
    theme(legend.position = 'top')
```

----

# Age

```{r age, fig.height = 5}
# Age by study site
demo %>%
    group_by(Site) %>%
    summarise(count = sum(!is.na(Age)),
              missing = sum(is.na(Age)),
              mean = round(mean(Age), 1),
              sd = round(sd(Age), 1),
              range = paste0(round(min(Age), 2), ' - ', 
                             round(max(Age), 2))) %>%
    knitr::kable(., 
                 caption = 'Age (years) by study site',
                 col.names = c('Site', 'Count', 'Missing', 'Mean', 
                               'SD', 'Range'),
                 align = 'lrrrrr')

# Plot 
ggplot(data = demo) +
    aes(y = Age,
        x = Site) +
    geom_boxplot(fill = '#666666',
                 colour = '#000000') +
    labs(title = 'Participant age',
         subtitle = 'Conditioned on study site',
         y = 'Age (years)',
         x = 'Study site') +
    theme(legend.position = 'none')

# Age by study site and intervention group
demo %>%
    group_by(Site, Group) %>%
    summarise(count = sum(!is.na(Age)),
              missing = sum(is.na(Age)),
              mean = round(mean(Age), 1),
              sd = round(sd(Age), 1),
              range = paste0(round(min(Age), 2), ' - ', 
                             round(max(Age), 2))) %>%
    knitr::kable(., 
                 caption = 'Age (years) by intervention group at each study site',
                 col.names = c('Site', 'Group', 'Count', 'Missing', 
                               'Mean', 'SD', 'Range'),
                 align = 'llrrrrr')

# Plot 
ggplot(data = demo) +
    aes(y = Age,
        x = Group,
        fill = Group) +
    geom_boxplot(position = position_dodge(0)) +
    labs(title = 'Participant age',
         subtitle = 'Conditioned on intervention group and study site',
         y = 'Age (years)',
         x = 'Intervention group') +
    scale_fill_brewer(name = 'Intervention group: ',
                      type = 'qual',
                      palette = 'Dark2') +
    facet_wrap(~ Site, 
               ncol = 4, 
               labeller = label_both) +
    theme(legend.position = 'top')
```

----

# CD4 T-cell count

### First recorded CD4

```{r first_cd4, fig.height = 5}
# First CD4 by study site
demo %>%
    group_by(Site) %>%
    summarise(count = sum(!is.na(CD4)),
              missing = sum(is.na(CD4)),
              median = round(median(CD4, na.rm = TRUE)),
              IQR = paste0(round(quantile(CD4, prob = 0.25, na.rm = TRUE)), ' - ', 
                           round(quantile(CD4, prob = 0.75, na.rm = TRUE)))) %>%
    knitr::kable(., 
                 caption = 'First recorded CD4 (cells/ul) by study site',
                 col.names = c('Site', 'Count', 'Missing','Median', 'IQR'),
                 align = 'lrrrr')

# Plot
ggplot(data = demo) +
    aes(y = CD4,
        x = Site) +
    geom_boxplot(fill = '#666666',
                 colour = '#000000') +
    labs(title = 'First recorded CD4 T-cell count',
         subtitle = 'Conditioned on study site',
         caption = '(Missing data: see table for details)',
         y = expression(CD4~count~(cells/mu*l)),
         x = 'Study site') +
    theme(legend.position = 'none')

# First CD4 by study site and intervention group
demo %>%
    group_by(Site, Group) %>%
    summarise(count = sum(!is.na(CD4)),
              missing = sum(is.na(CD4)),
              median = round(median(CD4, na.rm = TRUE)),
              IQR = paste0(round(quantile(CD4, prob = 0.25, na.rm = TRUE)), ' - ', 
                           round(quantile(CD4, prob = 0.75, na.rm = TRUE)))) %>%
    knitr::kable(., 
                 caption = 'First recorded CD4 (cells/ul) by intervention group at each study site',
                 col.names = c('Site', 'Group', 'Count', 'Missing', 
                               'Median', 'IQR'),
                 align = 'llrrrr')

# Plot
ggplot(data = demo) +
    aes(y = CD4,
        x = Group,
        fill = Group) +
    geom_boxplot(position = position_dodge(0)) +
    labs(title = 'First recorded CD4 T-cell count',
         subtitle = 'Conditioned on intervention group and study site',
         caption = '(Missing data: see table for details)',
         y = expression(CD4~count~(cells/mu*l)),
         x = 'Group') +
    scale_fill_brewer(name = 'Intervention group: ',
                      type = 'qual',
                      palette = 'Dark2') +
    facet_wrap(~ Site, 
               ncol = 4, 
               labeller = label_both) +
    theme(legend.position = 'top')
```

### Latest CD4 (baseline)

```{r latest_cd4, fig.height = 5}
# Latest CD4 by study site
demo %>%
    group_by(Site) %>%
    summarise(count = sum(!is.na(CD4_recent)),
              missing = sum(is.na(CD4_recent)),
              median = round(median(CD4_recent, na.rm = TRUE)),
              IQR = paste0(round(quantile(CD4_recent, prob = 0.25, na.rm = TRUE)), ' - ', 
                           round(quantile(CD4_recent, prob = 0.75, na.rm = TRUE)))) %>%
    knitr::kable(., 
                 caption = 'Latest recorded CD4 (cells/ul) by study site',
                 col.names = c('Site', 'Count','Missing', 'Median', 'IQR'),
                 align = 'lrrrr')

# Plot
ggplot(data = demo) +
    aes(y = CD4_recent,
        x = Site) +
    geom_boxplot(fill = '#666666',
                 colour = '#000000') +
    labs(title = 'Latest recorded CD4 T-cell count',
         subtitle = 'Conditioned on study site',
         caption = '(Missing data: see tables for details)',
         y = expression(CD4~count~(cells/mu*l)),
         x = 'Study site') +
    theme(legend.position = 'none')

# Latest CD4 by study site and intervention group
demo %>%
    group_by(Site, Group) %>%
    summarise(count = sum(!is.na(CD4_recent)),
              missing = sum(is.na(CD4_recent)),
              median = round(median(CD4_recent, na.rm = TRUE)),
              IQR = paste0(round(quantile(CD4_recent, prob = 0.25, na.rm = TRUE)), ' - ', 
                           round(quantile(CD4_recent, prob = 0.75, na.rm = TRUE)))) %>%
    knitr::kable(., 
                 caption = 'Latest recorded CD4 (cells/ul) by intervention group at each study site',
                 col.names = c('Site', 'Group', 'Count', 'Missing', 
                               'Median', 'IQR'),
                 align = 'llrrrr')

# Plot
ggplot(data = demo) +
    aes(y = CD4_recent,
        x = Group,
        fill = Group) +
    geom_boxplot(position = position_dodge(0)) +
    labs(title = 'Latest recorded CD4 T-cell count',
         subtitle = 'Conditioned on intervention group and study site',
         caption = '(Missing data: see tables for details)',
         y = expression(CD4~count~(cells/mu*l)),
         x = 'Group') +
    scale_fill_brewer(name = 'Intervention group: ',
                      type = 'qual',
                      palette = 'Dark2') +
    facet_wrap(~ Site, 
               ncol = 4, 
               labeller = label_both) +
    theme(legend.position = 'top') 
```

----

# Employment status

```{r occupation, fig.width = 10, fig.height = 5}
# Occupation by study site
demo %>%
    group_by(Site, Occupation) %>%
    summarise(count = sum(!is.na(Occupation)),
              missing = sum(is.na(Occupation))) %>%
    group_by(Site) %>%
    mutate(percent = round((count / sum(count)) * 100, 1)) %>%
    mutate(count = case_when(
        count > missing ~ count,
        TRUE ~ missing
        ),
        percent = case_when(
            percent > 0 ~ as.character(percent),
            TRUE ~ '-'
            ),
        Occupation = case_when(
        is.na(Occupation) ~ 'missing data',
        TRUE ~ Occupation
        )) %>% 
    select(-missing) %>% 
    knitr::kable(., 
                 caption = 'Employment status by study site',
                 col.names = c('Site', 'Employment status', 'Count', 'Percent'),
                 align = 'llrr')

# Plot 
demo %>%
    filter(!is.na(Occupation)) %>%
    ggplot(data = .) +
    aes(x = Site,
        colour = Occupation,
        fill = Occupation) +
    geom_bar(position = position_fill()) +
    labs(title = 'Employment status',
         subtitle = 'Conditioned on study site',
         caption = '(Missing data: see table for details)',
         y = 'Proportion',
         x = 'Study site') +
    scale_fill_brewer(name = 'Employment status: ',
                      type = 'qual',
                      palette = 'Dark2') +
    scale_colour_brewer(name = 'Employment status: ',
                        type = 'qual',
                        palette = 'Dark2') 

# Occupation by study site and intervention group
demo %>%
    group_by(Site, Group, Occupation) %>%
    summarise(count = sum(!is.na(Occupation)),
              missing = sum(is.na(Occupation))) %>%
    group_by(Site) %>%
    mutate(percent = round((count / sum(count)) * 100, 1)) %>%
    mutate(count = case_when(
        count > missing ~ count,
        TRUE ~ missing
        ),
        percent = case_when(
            percent > 0 ~ as.character(percent),
            TRUE ~ '-'
            ),
        Occupation = case_when(
        is.na(Occupation) ~ 'missing data',
        TRUE ~ Occupation
        )) %>% 
    select(-missing) %>% 
    knitr::kable(., 
                 caption = 'Employment status by intervention group at each study site',
                 col.names = c('Site', 'Group', 'Employment status', 
                               'Count', 'Percent'),
                 align = 'lllrr')

# Plot
demo %>%
    filter(!is.na(Occupation)) %>%
    ggplot(data = .) +
    aes(x = Group,
        fill = Occupation) +
    geom_bar(position = position_fill()) +
    labs(title = 'Employment status',
         subtitle = 'Conditioned on intervention group and study site',
         caption = '(Missing data: see table for details)',
         y = 'Proportion',
         x = 'Group') +
    scale_fill_brewer(name = 'Employment status: ',
                      type = 'qual',
                      palette = 'Dark2') +
    facet_wrap(~ Site, 
               ncol = 4, 
               labeller = label_both)
```

----

# Years of education

```{r education1, fig.width = 10, fig.height = 5}
# Education by study site
## R1
demo %>%
    filter(Site == 'R1') %>%
    group_by(Site, Years_education) %>%
    summarise(count = sum(!is.na(Years_education)),
              missing = sum(is.na(Years_education))) %>%
    group_by(Site) %>%
    mutate(percent = round((count / sum(count)) * 100, 1),
           percent = sprintf('%.1f', percent)) %>%
    mutate(Years_education = as.character(Years_education),
           Years_education = case_when(
        is.na(Years_education) ~ 'Missing data',
        TRUE ~ Years_education
        ),
        count = case_when(
            count > 0 ~ count,
            TRUE ~ missing
        ),
        percent = case_when(
            percent == '0.0' ~ '-',
            TRUE ~ percent
        )) %>% 
    ungroup() %>% 
    select(-Site, -missing) %>% 
    mutate(Years_education = factor(Years_education,
                                    levels = c(as.character(0:12), '12+'),
                                    ordered = TRUE)) %>% 
    knitr::kable(., 
                 caption = 'R1: Years of education by study site',
                 col.names = c('Years of education', 'Count', 'Percent'),
                 align = 'lrr')

## R2
demo %>%
    filter(Site == 'R2') %>%
   group_by(Site, Years_education) %>%
    summarise(count = sum(!is.na(Years_education)),
              missing = sum(is.na(Years_education))) %>%
    group_by(Site) %>%
    mutate(percent = round((count / sum(count)) * 100, 1),
           percent = sprintf('%.1f', percent)) %>%
    mutate(Years_education = as.character(Years_education),
           Years_education = case_when(
        is.na(Years_education) ~ 'Missing data',
        TRUE ~ Years_education
        ),
        count = case_when(
            count > 0 ~ count,
            TRUE ~ missing
        ),
        percent = case_when(
            percent == '0.0' ~ '-',
            TRUE ~ percent
        )) %>% 
    ungroup() %>% 
    select(-Site, -missing) %>% 
    mutate(Years_education = factor(Years_education,
                                    levels = c(as.character(0:12), '12+'),
                                    ordered = TRUE)) %>% 
    knitr::kable(., 
                 caption = 'R2: Years of education by study site',
                 col.names = c('Years of education', 'Count', 'Percent'),
                 align = 'lrr')
## U1
demo %>%
    filter(Site == 'U1') %>%
    group_by(Site, Years_education) %>%
    summarise(count = sum(!is.na(Years_education)),
              missing = sum(is.na(Years_education))) %>%
    group_by(Site) %>%
    mutate(percent = round((count / sum(count)) * 100, 1),
           percent = sprintf('%.1f', percent)) %>%
    mutate(Years_education = as.character(Years_education),
           Years_education = case_when(
        is.na(Years_education) ~ 'Missing data',
        TRUE ~ Years_education
        ),
        count = case_when(
            count > 0 ~ count,
            TRUE ~ missing
        ),
        percent = case_when(
            percent == '0.0' ~ '-',
            TRUE ~ percent
        )) %>% 
    ungroup() %>% 
    select(-Site, -missing) %>% 
    mutate(Years_education = factor(Years_education,
                                    levels = c(as.character(0:12), 
                                               '12+', 'Missing data'),
                                    ordered = TRUE)) %>% 
    knitr::kable(., 
                 caption = 'U1: Years of education by study site',
                 col.names = c('Years of education', 'Count', 'Percent'),
                 align = 'lrr')

## U2
demo %>%
    filter(Site == 'U2') %>%
    group_by(Site, Years_education) %>%
    summarise(count = sum(!is.na(Years_education)),
              missing = sum(is.na(Years_education))) %>%
    group_by(Site) %>%
    mutate(percent = round((count / sum(count)) * 100, 1),
           percent = sprintf('%.1f', percent)) %>%
    mutate(Years_education = as.character(Years_education),
           Years_education = case_when(
        is.na(Years_education) ~ 'Missing data',
        TRUE ~ Years_education
        ),
        count = case_when(
            count > 0 ~ count,
            TRUE ~ missing
        ),
        percent = case_when(
            percent == '0.0' ~ '-',
            TRUE ~ percent
        )) %>% 
    ungroup() %>% 
    select(-Site, -missing) %>% 
    mutate(Years_education = factor(Years_education,
                                    levels = c(as.character(0:12), 
                                               '12+', 'Missing data'),
                                    ordered = TRUE)) %>% 
    knitr::kable(., 
                 caption = 'U2: Years of education by study site',
                 col.names = c('Years of education', 'Count', 'Percent'),
                 align = 'lrr')

# Plot
demo %>%
    filter(!is.na(Years_education)) %>%
    group_by(Site, Years_education) %>% 
    summarise(count = n()) %>%
    group_by(Site) %>% 
    mutate(proportion = count / sum(count)) %>% 
    ggplot(data = .) +
    aes(y = proportion,
        x = Years_education) +
    geom_bar(stat = 'identity') +
    labs(title = 'Years of education', 
         subtitle = 'Conditioned on study site',
         caption = '(Missing data: see tables for details)',
         x = 'Years of educations',
         y = 'Proportion') +
    facet_wrap(~ Site,
               ncol = 4,
               labeller = label_both)
```

```{r education2, fig.height = 8, fig.width = 10}
# Education by intervention group at each study site
## R1
demo %>%
    filter(Site == 'R1') %>%
    group_by(Site, Group, Years_education) %>%
    summarise(count = sum(!is.na(Years_education)),
              missing = sum(is.na(Years_education))) %>%
    group_by(Site) %>%
    mutate(percent = round((count / sum(count)) * 100, 1),
           percent = sprintf('%.1f', percent)) %>%
    mutate(Years_education = as.character(Years_education),
           Years_education = case_when(
        is.na(Years_education) ~ 'Missing data',
        TRUE ~ Years_education
        ),
        count = case_when(
            count > 0 ~ count,
            TRUE ~ missing
        ),
        percent = case_when(
            percent == '0.0' ~ '-',
            TRUE ~ percent
        )) %>% 
    ungroup() %>% 
    select(-Site, -missing) %>% 
    mutate(Years_education = factor(Years_education,
                                    levels = c(as.character(0:12), 
                                               '12+', 'Missing data'),
                                    ordered = TRUE)) %>% 
    knitr::kable(., 
                 caption = 'R1: Years of education by study site',
                 col.names = c('Years of education', 'Group', 'Count', 'Percent'),
                 align = 'llrr')

## R2
demo %>%
    filter(Site == 'R2') %>%
    group_by(Site, Years_education) %>%
    summarise(count = sum(!is.na(Years_education)),
              missing = sum(is.na(Years_education))) %>%
    group_by(Site) %>%
    mutate(percent = round((count / sum(count)) * 100, 1),
           percent = sprintf('%.1f', percent)) %>%
    mutate(Years_education = as.character(Years_education),
           Years_education = case_when(
        is.na(Years_education) ~ 'Missing data',
        TRUE ~ Years_education
        ),
        count = case_when(
            count > 0 ~ count,
            TRUE ~ missing
        ),
        percent = case_when(
            percent == '0.0' ~ '-',
            TRUE ~ percent
        )) %>% 
    ungroup() %>% 
    select(-Site, -missing) %>% 
    mutate(Years_education = factor(Years_education,
                                    levels = c(as.character(0:12), 
                                               '12+', 'Missing data'),
                                    ordered = TRUE)) %>% 
    knitr::kable(., 
                 caption = 'R2: Years of education by study site',
                 col.names = c('Years of education', 'Count', 'Percent'),
                 align = 'lrr')
## U1
demo %>%
    filter(Site == 'U1') %>%
    group_by(Site, Group, Years_education) %>%
    summarise(count = sum(!is.na(Years_education)),
              missing = sum(is.na(Years_education))) %>%
    group_by(Site) %>%
    mutate(percent = round((count / sum(count)) * 100, 1),
           percent = sprintf('%.1f', percent)) %>%
    mutate(Years_education = as.character(Years_education),
           Years_education = case_when(
        is.na(Years_education) ~ 'Missing data',
        TRUE ~ Years_education
        ),
        count = case_when(
            count > 0 ~ count,
            TRUE ~ missing
        ),
        percent = case_when(
            percent == '0.0' ~ '-',
            TRUE ~ percent
        )) %>% 
    ungroup() %>% 
    select(-Site, -missing) %>% 
    mutate(Years_education = factor(Years_education,
                                    levels = c(as.character(0:12), 
                                               '12+', 'Missing data'),
                                    ordered = TRUE)) %>% 
    knitr::kable(., 
                 caption = 'U1: Years of education by study site',
                 col.names = c('Years of education', 'Group', 'Count', 'Percent'),
                 align = 'llrr')

## U2
demo %>%
    filter(Site == 'U2') %>%
    group_by(Site, Group, Years_education) %>%
    summarise(count = sum(!is.na(Years_education)),
              missing = sum(is.na(Years_education))) %>%
    group_by(Site) %>%
    mutate(percent = round((count / sum(count)) * 100, 1),
           percent = sprintf('%.1f', percent)) %>%
    mutate(Years_education = as.character(Years_education),
           Years_education = case_when(
        is.na(Years_education) ~ 'Missing data',
        TRUE ~ Years_education
        ),
        count = case_when(
            count > 0 ~ count,
            TRUE ~ missing
        ),
        percent = case_when(
            percent == '0.0' ~ '-',
            TRUE ~ percent
        )) %>% 
    ungroup() %>% 
    select(-Site, -missing) %>% 
    mutate(Years_education = factor(Years_education,
                                    levels = c(as.character(0:12), 
                                               '12+', 'Missing data'),
                                    ordered = TRUE)) %>% 
    knitr::kable(., 
                 caption = 'U2: Years of education by study site',
                 col.names = c('Years of education', 'Group', 'Count', 'Percent'),
                 align = 'llrr')

# Plot
demo %>%
    filter(!is.na(Years_education)) %>%
    group_by(Site, Group, Years_education) %>% 
    summarise(count = n()) %>%
    group_by(Site, Group) %>% 
    mutate(proportion = count / sum(count)) %>% 
    ggplot(data = .) +
    aes(y = proportion,
        x = Years_education,
        fill = Group) +
    geom_bar(stat = 'identity') +
    labs(title = 'Years of education', 
         subtitle = 'Conditioned on intervention group and study site',
         caption = '(Missing data: see tables for details)',
         x = 'Years of educations',
         y = 'Proportion') +
    scale_fill_brewer(type = 'qual',
                      palette = 'Dark2') +
    facet_grid(Group ~ Site,
               labeller = label_both) +
    theme(legend.position = 'none')
```

----

# SOS health literacy

```{r health_literacy, fig.height = 5}
# Health literacy by study site
demo %>%
    group_by(Site, SOS_mnemonic) %>%
    summarise(count = sum(!is.na(SOS_mnemonic)),
              missing = sum(is.na(SOS_mnemonic))) %>%
    group_by(Site) %>%
    mutate(percent = round((count / sum(count)) * 100, 1),
           percent = sprintf('%.1f', percent)) %>%
    mutate(SOS_mnemonic = case_when(
        is.na(SOS_mnemonic) ~ 'Missing data',
        TRUE ~ SOS_mnemonic
        ),
        count = case_when(
            count > 0 ~ count,
            TRUE ~ missing
        ),
        percent = case_when(
            percent == 'NaN' ~ '-',
            TRUE ~ percent
        )) %>% 
    mutate(SOS_mnemonic = factor(SOS_mnemonic,
                                 levels = c('hl', 'lhl', 'Missing data')),
           SOS_mnemonic = fct_recode(SOS_mnemonic,
                                     'Health literate' = 'hl',
                                     'Low health literacy' = 'lhl')) %>%
    select(-missing) %>% 
    knitr::kable(., 
                 caption = 'SOS health literacy by study site',
                 col.names = c('Site', 'Literacy state', 'Count', 'Percent'),
                 align = 'llrr')

# Plot 
demo %>%
    filter(!is.na(SOS_mnemonic)) %>%
    ggplot(data = .) +
    aes(x = Site,
        colour = SOS_mnemonic,
        fill = SOS_mnemonic) +
    geom_bar(position = position_fill()) +
    labs(title = 'Health literacy',
         subtitle = 'Conditioned on study site',
         caption = 'Missing data: see tables for details',
         y = 'Proportion',
         x = 'Study site') +
    scale_fill_brewer(name = 'Literacy status: ',
                      labels = c('Health literate', 'Low health literacy'),
                      type = 'qual',
                      palette = 'Dark2') +
    scale_colour_brewer(name = 'Literacy status: ',
                        labels = c('Health literate', 'Low health literacy'),
                        type = 'qual',
                        palette = 'Dark2') +
    theme(legend.position = 'top')

# Health literacy by study site and intervention group
demo %>%
    group_by(Site, Group, SOS_mnemonic) %>%
    summarise(count = sum(!is.na(SOS_mnemonic)),
              missing = sum(is.na(SOS_mnemonic))) %>%
    group_by(Site) %>%
    mutate(percent = round((count / sum(count)) * 100, 1),
           percent = sprintf('%.1f', percent)) %>%
    mutate(SOS_mnemonic = case_when(
        is.na(SOS_mnemonic) ~ 'Missing data',
        TRUE ~ SOS_mnemonic
        ),
        count = case_when(
            count > 0 ~ count,
            TRUE ~ missing
        ),
        percent = case_when(
            percent == 'NaN' ~ '-',
            TRUE ~ percent
        )) %>% 
    mutate(SOS_mnemonic = factor(SOS_mnemonic,
                                 levels = c('hl', 'lhl', 'Missing data')),
           SOS_mnemonic = fct_recode(SOS_mnemonic,
                                     'Health literate' = 'hl',
                                     'Low health literacy' = 'lhl')) %>%
    select(-missing) %>% 
    knitr::kable(., 
                 caption = 'SOS health literacy by intervention group at each study site',
                 col.names = c('Site', 'Group', 'Literacy state', 
                               'Count', 'Percent'),
                 align = 'lllrr')

# Plot 
demo %>%
    filter(!is.na(SOS_mnemonic)) %>%
    ggplot(data = .) +
    aes(x = Group,
        colour = SOS_mnemonic,
        fill = SOS_mnemonic) +
    geom_bar(position = position_fill()) +
    labs(title = 'Health literacy',
         subtitle = 'Conditioned on intervention group and study site',
         caption = '(Missing data: see table for details)',
         y = 'Proportion',
         x = 'Group') +
    scale_fill_brewer(name = 'Literacy status: ',
                      labels = c('Health literate', 'Low health literacy'),
                      type = 'qual',
                      palette = 'Dark2') +
    scale_colour_brewer(name = 'Literacy status: ',
                        labels = c('Health literate', 'Low health literacy'),
                        type = 'qual',
                        palette = 'Dark2') +
    theme(legend.position = 'top') +
    facet_wrap(~ Site, 
               ncol = 4, 
               labeller = label_both)
```

----

# Session information

```{r session_info, echo = FALSE}
sessionInfo()
```