---
title: "BDI analysis"
author: "Peter Kamerman, Tory Madden, and Antonia Wadley"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
    html_document:
        theme: yeti
        highlight: pygments
        df_print: paged
        toc: true
        toc_float: true
        code_folding: show
---

```{r setup, include = FALSE}
# Load packages
library(dplyr)
library(ggplot2)
library(tidyr)

# Set knitr options
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      fig.align = 'center',
                      fig.width = 8,
                      fig.height = 8)
```

## Import data
```{r import_data, results = 'hide'}
# Read in bdi data
bdi <- readr::read_rds('./data/bdi.rds') %>%
    arrange(ID) %>%
    mutate(ID = stringr::str_to_lower(ID))

# Read in site and group info
foo <- readr::read_rds('./data/demographics.rds') %>%
    select(ID, Site, Group, Sex) %>%
    rename(ID2 = ID) %>%
    arrange(ID2)

# Join the two datasets 
bdi <- foo %>%
    bind_cols(bdi) %>%
    rowwise() %>%
    mutate(ID_match = ifelse(ID2 == ID,
                             yes = TRUE,
                             no = FALSE))

# Check for mismatches from join
nrow(filter(bdi, ID_match == FALSE))

# Eliminate extra ID column
bdi <- bdi %>%
    select(-ID,
           -ID_match) %>%
    rename(ID = ID2)
```

## Quick look    
```{r quick_look}    
glimpse(bdi)
head(bdi)
tail(bdi)
```

## Process data 
### Calculate total BDI scores
```{r total_bdi score}
# Create new column (total BDI score for each time point) by summing
# scores for each time point
bdi_BL <- bdi %>% select(contains('BL'))
bdi$total_BL <- rowSums(bdi_BL)

bdi_Wk4 <- bdi %>% select(matches('Wk4$'))
bdi$total_Wk4 <- rowSums(bdi_Wk4) 

bdi_Wk8 <- bdi %>% select(contains('Wk8'))
bdi$total_Wk8 <- rowSums(bdi_Wk8)

bdi_Wk12 <- bdi %>% select(contains('Wk12'))
bdi$total_Wk12 <- rowSums(bdi_Wk12) 

bdi_Wk24 <- bdi %>% select(contains('Wk24'))
bdi$total_Wk24 <- rowSums(bdi_Wk24) 

bdi_Wk48 <- bdi %>% select(contains('Wk48'))
bdi$total_Wk48 <- rowSums(bdi_Wk48) 

# Check
glimpse(bdi)
```

## Clean data
```{r clean_data}
# Gather from wide format into long format
bdi <- bdi %>%
    tidyr::gather(key = bdi_question,
                  value = bdi_rating,
                  -ID, - Site, - Group, -Sex)

# Separate by date
bdi <- bdi %>%
    mutate(bdi_question = stringr::str_replace_all(bdi_question,
                                                   pattern = 'Int_s',
                                                   replacement = 'S'),
           bdi_question = stringr::str_replace_all(bdi_question,
                                                   pattern = 'Past_f',
                                                   replacement = 'PF'),
           bdi_question = stringr::str_replace_all(bdi_question,
                                                   pattern = 'Loss_p',
                                                   replacement = 'LP'),
           bdi_question = stringr::str_replace_all(bdi_question,
                                                   pattern = 'Self_d',
                                                   replacement = 'SD'),
           bdi_question = stringr::str_replace_all(bdi_question,
                                                   pattern = 'Self_c',
                                                   replacement = 'SC'),
           bdi_question = stringr::str_replace_all(bdi_question,
                                                   pattern = 'Loss_i',
                                                   replacement = 'LI'),
           bdi_question = stringr::str_replace_all(bdi_question,
                                                   pattern = 'Loss_e',
                                                   replacement = 'LE')) %>%
    separate(bdi_question, c('question', 'time_point'), sep = '_')

# Set levels for time_points        
bdi <- bdi %>% mutate(time_point = factor(time_point,
                                          levels = c('BL', 'Wk4', 'Wk8', 
                                                     'Wk12', 'Wk24', 'Wk48'),
                                          ordered = TRUE))

# Get totals 
bdi_tot <- filter(bdi, question == 'total')

glimpse(bdi_tot)
```

## Plots
Note: Clinical cut-off points are marked by lines
```{r plots}
# Create new column with time
bdi_tot <- bdi_tot %>% 
    mutate(Week = case_when(
        stringr::str_detect(.$time_point, "Wk48")  ~ 48,
        stringr::str_detect(.$time_point, "BL")  ~ 0,
        stringr::str_detect(.$time_point, "Wk4$")  ~ 4,
        stringr::str_detect(.$time_point, "Wk8")  ~ 8,
        stringr::str_detect(.$time_point, "Wk12")  ~ 12,
        stringr::str_detect(.$time_point, "Wk24")  ~ 24
    ))

# Check column contents
unique(bdi_tot$Week)  

# Delete time_point column
bdi_tot <- bdi_tot %>% select(-time_point)
```

### Spaghetti plots
```{r spag_plots}
ggplot(data = bdi_tot) +
    aes(x = Week,
        y = bdi_rating,
        colour = Site,
        group = ID) %>%
    geom_line() +
    labs(title = 'Beck depression inventory',
         subtitle = 'Colour by site') +
    theme(legend.position = 'right') +
              scale_x_continuous(breaks = c(0,4,8,12,24,48),
                                 limits = c(0,48)) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2)
    
ggplot(data = bdi_tot) +
    aes(x = Week,
        y = bdi_rating,
        colour = ID,
        group = ID) %>%
    geom_line() +
    facet_grid(Site ~ .) +
    labs(title = 'Beck depression inventory',
         subtitle = 'Facet by site, colour by ID') +
    theme(legend.position = 'none') +
    scale_x_continuous(breaks = c(0,4,8,12,24,48),
                       limits = c(0,48)) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2)

ggplot(data = bdi_tot) +
    aes(x = Week,
        y = bdi_rating,
        colour = Sex,
        group = ID) %>%
    geom_line() +
    labs(title = 'Beck depression inventory',
         subtitle = 'Colour by gender') +
    theme(legend.position = 'right') +
    scale_x_continuous(breaks = c(0,4,8,12,24,48),
                       limits = c(0,48)) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2)

bdi_tot %>% filter(Site == 'u1') %>%    
    ggplot(.) +
    aes(x = Week,
        y = bdi_rating,
        colour = Group,
        group = ID) %>%
    geom_line() +
    facet_grid(Site ~ .) +
    labs(title = 'Site J: Beck depression inventory',
         subtitle = 'Colour by Group') +
    theme(legend.position = 'right') +
    scale_x_continuous(breaks = c(0,4,8,12,24,48),
                       limits = c(0,48)) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2)  

bdi_tot %>% filter(Site == 'u1') %>%    
ggplot(.) +
    aes(x = Week,
        y = bdi_rating,
        colour = ID,
        group = ID) %>%
    geom_line() +
    facet_grid(Site ~ .) +
    labs(title = 'Site J: Beck depression inventory',
         subtitle = 'Colour by ID') +
    theme(legend.position = 'none') +
    scale_x_continuous(breaks = c(0,4,8,12,24,48),
                       limits = c(0,48)) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2)   

bdi_tot %>% filter(Site == 'r1') %>%    
    ggplot(.) +
    aes(x = Week,
        y = bdi_rating,
        colour = Group,
        group = ID) %>%
    geom_line() +
    facet_grid(Site ~ .) +
    labs(title = 'Site M: Beck depression inventory',
         subtitle = 'Colour by Group') +
    theme(legend.position = 'right') +
    scale_x_continuous(breaks = c(0,4,8,12,24,48),
                       limits = c(0,48)) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2)  

bdi_tot %>% filter(Site == 'r1') %>%    
    ggplot(.) +
    aes(x = Week,
        y = bdi_rating,
        colour = ID,
        group = ID) %>%
    geom_line() +
    facet_grid(Site ~ .) +
    labs(title = 'Site M: Beck depression inventory',
         subtitle = 'Colour by ID') +
    theme(legend.position = 'none') +
    scale_x_continuous(breaks = c(0,4,8,12,24,48),
                       limits = c(0,48)) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2)  

bdi_tot %>% filter(Site == 'u2') %>%    
    ggplot(.) +
    aes(x = Week,
        y = bdi_rating,
        colour = Group,
        group = ID) %>%
    geom_line() +
    facet_grid(Site ~ .) +
    labs(title = 'Site R: Beck depression inventory',
         subtitle = 'Colour by Group') +
    theme(legend.position = 'right') +
    scale_x_continuous(breaks = c(0,4,8,12,24,48),
                       limits = c(0,48)) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2)  

bdi_tot %>% filter(Site == 'u2') %>%    
    ggplot(.) +
    aes(x = Week,
        y = bdi_rating,
        colour = ID,
        group = ID) %>%
    geom_line() +
    facet_grid(Site ~ .) +
    labs(title = 'Site R: Beck depression inventory',
         subtitle = 'Colour by ID') +
    theme(legend.position = 'none') +
    scale_x_continuous(breaks = c(0,4,8,12,24,48),
                       limits = c(0,48)) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2)  

bdi_tot %>% filter(Site == 'r2') %>%    
    ggplot(.) +
    aes(x = Week,
        y = bdi_rating,
        colour = Group,
        group = ID) %>%
    geom_line() +
    facet_grid(Site ~ .) +
    labs(title = 'Site Z: Beck depression inventory',
         subtitle = 'Colour by Group') +
    theme(legend.position = 'right') +
    scale_x_continuous(breaks = c(0,4,8,12,24,48),
                       limits = c(0,48)) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2)  

bdi_tot %>% filter(Site == 'r2') %>%    
    ggplot(.) +
    aes(x = Week,
        y = bdi_rating,
        colour = ID,
        group = ID) %>%
    geom_line() +
    facet_grid(Site ~ .) +
    labs(title = 'Site Z: Beck depression inventory',
         subtitle = 'Colour by ID') +
    theme(legend.position = 'none') +
    scale_x_continuous(breaks = c(0,4,8,12,24,48),
                       limits = c(0,48)) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2)  
```

### Summary plots
```{r summary_plots}
ggplot(data = bdi_tot) +
    aes(x = as.factor(Week),
        y = bdi_rating,
        colour = Group,
        fill = Group) %>%
    geom_boxplot(alpha = 0.6) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2) +
    facet_grid(Site ~ .) +
    labs(title = 'Beck Depression Inventory (BDI)', 
         subtitle = 'Faceted by study site, coloured by group')

ggplot(data = bdi_tot) +
    aes(x = as.factor(Week),
        y = bdi_rating,
        colour = Sex,
        fill = Sex) %>%
    geom_boxplot(alpha = 0.6) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2) +
    facet_grid(Group ~ .) +
    labs(title = 'Beck Depression Inventory (BDI)', 
         subtitle = 'Faceted by study group, coloured by sex')

ggplot(data = bdi_tot) +
    aes(x = as.factor(Week),
        y = bdi_rating,
        colour = Sex,
        fill = Sex) %>%
    geom_boxplot(alpha = 0.6) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2) +
    facet_grid(Site ~ Group) +
    labs(title = 'Beck Depression Inventory (BDI)', 
         subtitle = 'Faceted by study site and group, coloured by sex')

ggplot(data = filter(bdi_tot, Sex == 'female')) +
    aes(x = as.factor(Week),
        y = bdi_rating) %>%
    geom_boxplot(alpha = 0.6) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2) +
    labs(title = 'Beck Depression Inventory (BDI)',
         subtitle = 'Women only')

ggplot(data = filter(bdi_tot, Sex == 'female' & Site != 'u1')) +
    aes(x = as.factor(Week),
        y = bdi_rating) %>%
    geom_boxplot(alpha = 0.6) +
    geom_hline(yintercept = c(10, 16, 20, 30, 40), size = 0.25, linetype = 2) +
    labs(title = 'Beck Depression Inventory (BDI)', 
         subtitle = 'Women only (excluding U1)')
```

## Session information
```{r session_info}
sessionInfo()
```