---
title: 'HIP: EQ5D anxiety and depression subscale vs BDI'
subtitle: "Correlational analysss"
author: "Peter Kamerman and Tory Madden"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: 
    html_document:
        theme: yeti
        keep_md: true
        highlight: pygments
        toc: true
        toc_float: true
        code_folding: show
---

```{r setup, include = FALSE}
# Load packages
library(magrittr)
library(tidyverse)
library(skimr)

# Set ggplot2 theme
theme_set(new = theme_bw(base_size = 14))

# Set knitr options
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      fig.retina = 2,
                      fig.align = 'center',
                      fig.path = 'figures/eq5d-v-bdi/',
                      fig.width = 7,
                      fig.height = 7)
```

----

Is there correlation between the two assessments of depression and anxiety, the single EQ5D anxiety/depression item or the composite BDI?

Scores were scaled before the correlation was performed.

----

# Import data

```{r import_data}
# Get BDI
bdi <- read_rds('./data/bdi.rds')

# Get EQ5D
eq5d <- read_rds('./data/eq5d.rds')
```

----

# Quick look

```{r quick_look}
glimpse(bdi)
glimpse(eq5d)
```

----

# Clean data

```{r clean_data}
# BDI 
bdi %<>%
    select(ID, ends_with('BL')) %>% 
    mutate_at(.vars = 2:22,
              .funs = as.integer) %>% 
    mutate(bdi_score = rowSums(x = .[2:22])) %>% 
    select(ID, bdi_score)


# EQ5D
eq5d %<>% 
    select(ID, ends_with('Anxiety_and_depression.BL'))

# Join objects
data <- eq5d %>%
    left_join(bdi) %>%
    # Rename columns
    rename(eq5d_score = Anxiety_and_depression.BL) %>%
    # Normalise data
    mutate(bdi_score = as.vector(scale(bdi_score)),
           eq5d_score = as.vector(scale(eq5d_score))) %>%
    # Filter incomplete cases
    filter(complete.cases(.))
```

----

# Exploratory plots

```{r plots}
# Plot
ggplot(data = data) +
    aes(x = bdi_score,
        y = eq5d_score) +
    geom_point() +
    labs(title = 'Scatterplot of EQ5D-3L depression and anxiet score vs BDI total score',
         subtitle = 'Both variables have been scaled',
         x = 'Scaled BDI total score',
         y = 'Scaled EQ5D anxiety and depression score')
```

----

# Correlation analysis

```{r correlation}
cor.test(y = data$eq5d_score,
         x = data$bdi_score,
         method = 'spearman')
```

----

There is a weak positive correlation between the two scores.

----

# Session information

```{r session_info, echo = FALSE}
sessionInfo()
```