---
title: "Numer needed to treat"
author: "Peter Kamerman and Tory Madden"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
    html_document:
        theme: yeti
        highlight: pygments
        df_print: paged
        toc: true
        toc_float: true
        code_folding: show
---

```{r setup, include = FALSE}
# Load packages
library(magrittr)
library(tidyverse)

# Set knitr options
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      fig.align = 'center',
                      fig.width = 8,
                      fig.height = 8)
```

## Import data
```{r import_data}
# Read in site and group info
info <- read_rds('./data/demographics.rds') %>%
    select(ID, Site, Group, Sex) %>%
    mutate(ID = stringr::str_to_upper(ID))

# Read in data files
data <- read_rds('./data/bpi.rds')

# Join to info 
nnt <- left_join(info, data)
```

## Quick look
```{r quick_look}
# Head
head(nnt)
```

## Process data 
```{r clean_data, results = 'hide'}
# Select baseline data columns
nnt %<>%
    # Select columns
    select(ID, Site, Group, 
           ends_with('BL'), ends_with('Wk48')) %>%
    select(ID, Site, Group, 
           starts_with('Worst'),
           starts_with('Least'), 
           starts_with('Avg'), 
           starts_with('Now')) 
```

The number of participants per study site is:

```{r echo = FALSE} 
knitr::kable(summarise(group_by(nnt, Site), 
                          'Samples size (n)' = n(),
                          'Baseline - actual (n)' = sum(!is.na(Worst_BL)), 
                          'Week 48 - actual (n)' = sum(!is.na(Worst_Wk48)),
                          'Difference (n)' = `Baseline - actual (n)` - 
                                             `Week 48 - actual (n)`))
```

```{r}
nnt_BOCF <- nnt %>%
    # Add BOCF 
    mutate(Worst_Wk48 = ifelse(is.na(Worst_Wk48),
                               yes = Worst_BL,
                               no = Worst_Wk48),
           Least_Wk48 = ifelse(is.na(Least_Wk48),
                               yes = Least_BL,
                               no = Least_Wk48),
           Avg_Wk48 = ifelse(is.na(Avg_Wk48),
                               yes = Avg_BL,
                               no = Avg_Wk48),
           Now_Wk48 = ifelse(is.na(Now_Wk48),
                               yes = Now_BL,
                               no = Now_Wk48))
    # Calculate PSS (mean score)
    #mutate(PSS_BL = rowMeans(.[c(4, 6, 8, 10)], na.rm = TRUE),
     #      PSS_Wk48 = rowMeans(.[c(5, 7, 9, 11)], na.rm = TRUE))
```


## Session information
```{r session_info}
sessionInfo()
```