---
title: "SE-6: Descriptive analyses"
author: "Tory Madden and Peter Kamerman"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
    html_document:
        theme: yeti
        highlight: pygments
        df_print: paged
        toc: true
        toc_float: true
        code_folding: show
---

```{r setup, include = FALSE}
# Load packages
library(dplyr)
library(ggplot2)
library(stringr)

# Set knitr options
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      fig.align = 'center')
```

## Import data
```{r import_data, results = 'hide'}
se6 <- readr::read_rds('./data/se6.rds') %>%
    arrange(ID) %>%
    mutate(ID = stringr::str_to_lower(ID))

# For site and group info
foo <- readr::read_rds('./data/demographics.rds') %>%
    select(ID, Site, Group, Sex) %>%
    rename(ID2 = ID) %>%
    arrange(ID2)

# Join the two datasets 
se6 <- foo %>%
    bind_cols(se6) %>%
    rowwise() %>%
    mutate(ID_match = ifelse(ID2 == ID,
                             yes = TRUE,
                             no = FALSE))

# Check for mismatches from join
nrow(filter(se6, ID_match == FALSE))

# Eliminate extra ID column
se6 <- se6 %>%
    select(-ID,
           -ID_match) %>%
    rename(ID = ID2)
```

## Quick look
```{r quick_look}
glimpse(se6)
head(se6)
tail(se6)
```

## Clean data
```{r clean_data}
# Calculate mean score for each time point
se6_BL <- se6 %>% select(contains('BL'))
se6$mean_BL <- rowMeans(se6_BL, na.rm = TRUE)

se6_Wk4 <- se6 %>% select(contains('Wk4'))
se6$mean_Wk4 <- rowMeans(se6_Wk4, na.rm = TRUE)

se6_Wk8 <- se6 %>% select(contains('Wk8'))
se6$mean_Wk8 <- rowMeans(se6_Wk8, na.rm = TRUE)

se6_Wk12 <- se6 %>% select(contains('Wk12'))
se6$mean_Wk12 <- rowMeans(se6_Wk12, na.rm = TRUE)

se6_Wk24 <- se6 %>% select(contains('Wk24'))
se6$mean_Wk24 <- rowMeans(se6_Wk24, na.rm = TRUE)

se6_Wk48 <- se6 %>% select(contains('Wk48'))
se6$mean_Wk48 <- rowMeans(se6_Wk48, na.rm = TRUE)

# Check
glimpse(se6)

# Gather from wide format into long format
se6_tot <- se6 %>%
    tidyr::gather(key = se6_question,
                  value = se6_rating,
                  -ID, - Site, - Group, -Sex)
    
# Create columns for domain and time
se6_tot <- se6_tot %>%
    mutate(Domain = case_when(
        stringr::str_detect(.$se6_question, "Fatigue") ~ "Fatigue",
        stringr::str_detect(.$se6_question, "Discomf") ~ "Discomf",
        stringr::str_detect(.$se6_question, "Distress") ~ "Distress",
        stringr::str_detect(.$se6_question, "Other_sympt") ~ "Other_sympt",
        stringr::str_detect(.$se6_question, "Tasks") ~ "Tasks",
        stringr::str_detect(.$se6_question, "Non_drug") ~ "Non_drug",
        stringr::str_detect(.$se6_question, "mean") ~ "Mean"
    ))

se6_tot <- se6_tot %>% 
    mutate(Week = case_when(
        stringr::str_detect(.$se6_question, "Wk48")  ~ 48,
        stringr::str_detect(.$se6_question, "BL")  ~ 0,
        stringr::str_detect(.$se6_question, "Wk4$")  ~ 4,
        stringr::str_detect(.$se6_question, "Wk8")  ~ 8,
        stringr::str_detect(.$se6_question, "Wk12")  ~ 12,
        stringr::str_detect(.$se6_question, "Wk24")  ~ 24
    ))

# Check column contents
unique(se6_tot$Week) 
unique(se6_tot$Domain)

# Delete time_point column
se6_tot <- se6_tot %>% select(-se6_question)
```

## Plots
### Spaghetti plots
``` {r spag_plots}
se6_tot %>%
    filter(Domain == 'Mean') %>%
    ggplot(.) +
    aes(x = Week,
        y = se6_rating,
        group = ID,
        colour = Group) %>%
    geom_line(size = 0.4, 
              position = position_jitterdodge(dodge.width = 0.2)) +
    labs(title = 'Mean self-efficacy (SE-6)',
         subtitle = 'Coloured by group')

se6_tot %>%
    filter(Domain == 'Mean') %>%
    ggplot(.) +
    aes(x = Week,
        y = se6_rating,
        group = ID,
        colour = Group) %>%
    geom_line(size = 0.4, 
              position = position_jitterdodge(dodge.width = 0.2)) +
    facet_grid(Site ~.)
    labs(title = 'Mean self-efficacy (SE-6)',
         subtitle = 'Coloured by group, faceted by site')
    
se6_tot %>%
    filter(Domain == 'Mean') %>%
    ggplot(.) +
    aes(x = Week,
        y = se6_rating,
        group = ID,
        colour = Group) %>%
    geom_line(size = 0.4, 
              position = position_jitterdodge(dodge.width = 0.2)) +
    facet_grid(Site ~ Sex)
    labs(title = 'Mean self-efficacy (SE-6)',
         subtitle = 'Coloured by group, faceted by site and gender')
    
se6_tot %>%
    filter(Domain == 'Mean') %>%
    ggplot(.) +
    aes(x = Week,
        y = se6_rating,
        group = ID,
        colour = Sex) %>%
    geom_line(size = 0.4, 
              position = position_jitterdodge(dodge.width = 0.2)) +
    labs(title = 'Mean self-efficacy (SE-6)',
         subtitle = 'Coloured by gender')
```

### Summary plots
```{r summary_plots}
se6_tot %>% 
    filter(Domain == "Mean") %>%
    mutate(Week = as.factor(Week)) %>% # Reclassify 'Week' from numeric to factor
    ggplot(.) +
    aes(x = Week,
        y = se6_rating,
        colour = Group,
        fill = Group) %>%
    geom_boxplot(alpha = 0.6) +
    labs(title = 'Self-efficacy (SE-6)', 
         subtitle = 'Coloured by group')

se6_tot %>% 
    filter(Domain == "Mean") %>%
    mutate(Week = as.factor(Week)) %>% # Reclassify 'Week' from numeric to factor
    ggplot(.) +
    aes(x = Week,
        y = se6_rating,
        colour = Group,
        fill = Group) %>%
    geom_boxplot(alpha = 0.6) +
    facet_grid(Site ~ .) +
    labs(title = 'Self-efficacy (SE-6)', 
         subtitle = 'Faceted by study site, coloured by group')

se6_tot %>% 
    filter(Domain == "Mean") %>%
    mutate(Week = as.factor(Week)) %>% # Reclassify 'Week' from numeric to factor
    ggplot(.) +
    aes(x = Week,
        y = se6_rating,
        colour = Sex,
        fill = Sex) %>%
    geom_boxplot(alpha = 0.6) +
    facet_grid(Group ~ .) +
    labs(title = 'Self-efficacy (SE-6)', 
         subtitle = 'Faceted by study group, coloured by sex')

se6_tot %>% 
    filter(Domain == "Mean") %>%
    mutate(Week = as.factor(Week)) %>% # Reclassify 'Week' from numeric to factor
    ggplot(.) +
    aes(x = Week,
        y = se6_rating,
        colour = Sex,
        fill = Sex) %>%
    geom_boxplot(alpha = 0.6) +
    facet_grid(Site ~ Group) +
    labs(title = 'Self-efficacy (SE-6)', 
         subtitle = 'Faceted by study site and group, coloured by sex')

se6_tot %>% 
    filter(Domain == "Mean") %>%
    filter(Sex == "female") %>%
    mutate(Week = as.factor(Week)) %>% # Reclassify 'Week' from numeric to factor 
    ggplot(.) +
    aes(x = Week,
        y = se6_rating) %>%
    geom_boxplot(alpha = 0.6) +
    labs(title = 'Self-efficacy (SE-6)',
         subtitle = 'Women only')

se6_tot %>% 
    filter(Domain == "Mean") %>%
    filter(Sex == "female") %>%
    filter(Site != 'u1') %>%
    mutate(Week = as.factor(Week)) %>% # Reclassify 'Week' from numeric to factor 
    ggplot(.) +
    aes(x = Week,
        y = se6_rating) %>%
    geom_boxplot(alpha = 0.6) +
    labs(title = 'Self-efficacy (SE-6)', 
         subtitle = 'Women only (excluding U1)')

se6_tot %>%
    filter(Domain != 'mean') %>%
    ggplot(.) +
    aes(x = as.factor(Week),
        y = se6_rating,
        colour = Domain,
        fill = Domain) %>%
    geom_boxplot(alpha = 0.6) +
    labs(title = 'Self-efficacy domains',
         subtitle = 'Coloured by domain')

se6_tot %>%
    filter(Domain != 'mean') %>%
    ggplot(.) +
    aes(x = as.factor(Week),
        y = se6_rating,
        colour = Domain,
        fill = Domain) %>%
    geom_boxplot(alpha = 0.6) +
    facet_grid(Domain ~ .) +
    labs(title = 'Self-efficacy domains',
         subtitle = 'Faceted by domain')

se6_tot %>%
    filter(Domain != 'mean') %>%
    ggplot(.) +
    aes(x = as.factor(Week),
        y = se6_rating,
        colour = Group,
        fill = Group) %>%
    geom_boxplot(alpha = 0.6) +
    facet_grid(Domain ~ .) +
    labs(title = 'Self-efficacy domains',
         subtitle = 'Faceted by domain, coloured by group')

se6_tot %>%
    filter(Domain != 'mean') %>%
    ggplot(.) +
    aes(x = as.factor(Week),
        y = se6_rating,
        colour = Site,
        fill = Site) %>%
    geom_boxplot(alpha = 0.6) +
    facet_grid(Domain ~ .) +
    labs(title = 'Self-efficacy domains',
         subtitle = 'Faceted by domain, coloured by site')
```

## Session information
```{r session_info}
sessionInfo()
```