---
title: "Supplement 2"
subtitle: "Summary statistics for baseline variables"
author: "Peter Kamerman and Tory Madden"
date: "`r format(Sys.Date(), '%d %B %Y')`"
---

```{r setup, include = FALSE}
# Load packages
library(tidyverse)
library(magrittr)
library(rcompanion)
library(DescTools)
library(knitr)

# ggplot theme
theme_set(new = theme_bw(base_size = 16))

# Set knitr options
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      fig.path = 'figures/supplement-02-summary-statistics/')
```

----

Tabular summary statistics of baseline variables (time = 0 weeks) for the whole cohort, and stratified by sex and study site. 

----

# Import data

```{r import_data}
# Demographic data
demo <- read_rds('data-cleaned/demographics.rds')

# BDI
bdi <- read_rds('data-cleaned/bdi.rds')

# BPI
bpi <- read_rds('data-cleaned/bpi.rds')

# EQ5D
eq5d <- read_rds('data-cleaned/eq5d.rds') 

# SE6
se6 <- read_rds('data-cleaned/se6.rds')
```

----

# Process data

## Demographic data
```{r demographics}
demo %<>%
    # Convert sex to factor
    mutate(Sex = factor(Sex)) %>% 
    # Rename Years_on_ART
    rename(Years_on_HAART = Years_on_ART) %>% 
    # Convert SOS_mnemonic to factor
    mutate(SOS_mnemonic = factor(SOS_mnemonic)) %>% 
    # Transfer CD4_nadir data to CD4_recent if missing CD4_recent data 
    # (i.e. get the most updated CD4 count available)
    mutate(CD4_recent =
               ifelse(is.na(CD4_recent),
                      yes = CD4_nadir,
                      no = CD4_recent)) %>%
    # Categorise years of schooling into 7 years or less, 8-12 years, 
    # and more than 12 years of education, factorize, and then order 
    mutate(Education = case_when(
        Years_education <= 7 ~ '0-7 years',
        Years_education > 7 & Years_education <= 12 ~ '8-12 years',
        Years_education > 12 ~ 'More than 12 years'),
        Education = factor(Education,
                           levels = c('0-7 years',
                                      '8-12 years',
                                      'More than 12 years'),
                           ordered = TRUE)) %>%
    # Recode HAART and order
    mutate(HAART = case_when(
    HAART == 'first-line' ~ 'first-line HAART',
    HAART == 'second-line' ~ 'second-line HAART',
    HAART == 'monitoring' ~ 'no HAART'),
    HAART = factor(HAART,
                   levels = c('no HAART',
                              'first-line HAART', 
                              'second-line HAART'),
                   ordered = TRUE)) %>% 
    # Select required columns
    select(ID,
           Study_site,
           Sex,
           Age_years,
           Years_on_HAART,
           CD4_recent,
           HAART,
           Education,
           SOS_mnemonic)
```

## Beck's Depression Inventory
```{r becks}
bdi %<>%
    # Capitalize IDs
    mutate(ID = stringr::str_to_upper(ID)) %>%
    # Make a total score column
    mutate_at(2:ncol(bdi), 
              as.numeric) %>%
    mutate(BDI = rowSums(.[2:ncol(bdi)], na.rm = TRUE),
           # Treat BDI as a discrete scale
           BDI = round(BDI)) %>%
    select(ID,
           BDI)
```

## Brief Pain Inventory
```{r bpi}
bpi %<>%
    # Capitalize IDs
    mutate(ID = stringr::str_to_upper(ID)) %>%
    # Select baseline values
    select(ID,
           ends_with('BL')) %>%
    # Select columns
    select(ID, 
           3:6,
           9:15) %>%
    # Calculate Pain Severity Score (PSS) at baseline
    mutate(PSS = rowMeans(.[2:5], na.rm = TRUE),
           # Treat PSS as a discrete scale
           PSS = round(PSS)) %>%
    # Calculate Pain Interference Index (PIS) at baseline
    mutate(PIS = rowMeans(.[6:12], na.rm = TRUE),
           # Treat PIS as a discrete scale
           PIS = round(PIS)) %>%
    #remove unwanted columns
    select(ID,
           PSS,
           PIS)
```

## EQ-5D (3L)
```{r eq5d}
eq5d %<>%
    # Capitalize IDs
    mutate(ID = stringr::str_to_upper(ID)) 

# Calculate eq5d index score
## Create basic term = 1 for all cases in new column
eq5d$index_core <- 1

## Sum all rows for total index score
eq5d %<>% 
    mutate(index_sum = rowSums(.[2:6], na.rm = TRUE))

# Create constant term to subtract for domain scores > 1 (i.e. sum > 5)
eq5d %<>% 
    mutate(index_constant = ifelse(index_sum > 5, 
                                   yes = 0.081, 
                                   no = 0))

## Create variable for subtraction for each domain
eq5d %<>% 
    mutate(Mobility_index = ifelse(Mobility.BL == 2, 
                                   yes = 0.069,
                                   no = ifelse(Mobility.BL == 3, 
                                               yes = 0.314,
                                               no = 0))) %>% 
    mutate(Self_care_index = ifelse(Self_care.BL == 2,
                                    yes = 0.104,
                                    no = ifelse(Self_care.BL == 3, 
                                                yes = 0.214,
                                                no = 0))) %>% 
    mutate(Usual_activities_index = ifelse(Usual_activities.BL == 2, 
                                           yes = 0.036,
                                           no = ifelse(Usual_activities.BL == 3, 
                                                       yes = 0.094,
                                                       no = 0))) %>% 
    mutate(Pain_index = ifelse(Pain.BL == 2, 
                               yes = 0.123,
                               no = ifelse(Pain.BL == 3, 
                                           yes = 0.386,
                                           no = 0))) %>% 
    mutate(Anxiety_depression_index = ifelse(Anxiety_and_depression.BL == 2, 
                                             yes = 0.071,
                                             no = ifelse(Anxiety_and_depression.BL == 3, 
                                                         yes = 0.236,
                                                         no = 0)))

## Compute the index score using: 
## index = index_core - constant_index - Mobility_index...
eq5d %<>% 
    mutate(EQ5D_index = index_core - index_constant - Mobility_index 
           - Self_care_index - Usual_activities_index - Pain_index 
           - Anxiety_depression_index) %>% 
    # Convert State_of_health VAS to double
    mutate(EQ5D_VAS = as.numeric(State_of_health.BL))

# Select columns
eq5d %<>% select(ID,
                 EQ5D_index,
                 EQ5D_VAS)
```

## Self-efficacy Questionnaire 6
```{r se6}
se6 %<>%
    # Capitalize IDs
    mutate(ID = stringr::str_to_upper(ID)) %>%
    # Calculate SE6 at baseline
    mutate(SE6 = rowMeans(.[2:7], na.rm = TRUE),
           # Treat SE6 as a discrete scale
           SE6 = round(SE6)) %>%
    #remove unwanted columns
    select(ID,
           SE6)
```

## Bind all data together
```{r bind}
data <- demo %>% 
    left_join(bdi) %>% 
    left_join(bpi) %>% 
    left_join(eq5d) %>% 
    left_join(se6)
```

----

# Bespoke functions

Functions to calculate 95% confidence intervals of the difference in means, medians, and proportions.

```{r functions}
# Create arrays of combinations
pairs_site <- combn(x = c('R1', 'R2', 'U1', 'U2'),
                    m = 2)
pairs_sex <- combn(x = c('female', 'male'),
                   m = 2)

# Create a vector of pair_names 
pairs_names.sex <- 'female vs male'
pairs_names.site <- paste(pairs_site[1, ], 'vs', pairs_site[2, ])

# Define a list of length 6 (number of comparison pairs)
lst_sex <- vector(mode = 'list', length = 1)
lst_site <- vector(mode = 'list', length = 6)

# Define function for difference in means
delta_mean <- function(data, study_site = TRUE){
    if(study_site == TRUE){
        for(i in 1:6) {
            lst_site[[i]] <- t.test(x = data[[pairs_site[1, i]]],
                                    y = data[[pairs_site[2, i]]])[c(4)]
            
            lst_site[[i]] <- data_frame('Comparison' = pairs_names.site[[i]],
                                        Delta_CI.lower =
                                            round(lst_site[[i]]$conf.int[[1]], 2),
                                        Delta_CI.upper =
                                            round(lst_site[[i]]$conf.int[[2]], 2))
            out <- map_df(.x = lst_site,
                          ~ .x)
            }
    } else {
           lst_sex[[1]] <- t.test(x = data[[pairs_sex[1, 1]]],
                                  y = data[[pairs_sex[2, 1]]])[c(4)]
            
           lst_sex[[1]] <- data_frame('Comparison' = pairs_names.sex[[1]],
                                      Delta_CI.lower =
                                          round(lst_sex[[1]]$conf.int[[1]], 2),
                                      Delta_CI.upper =
                                          round(lst_sex[[1]]$conf.int[[2]], 2))
            out <- map_df(.x = lst_sex,
                          ~ .x) 
        }
    out
}

# Define function for difference in medians
delta_median <- function(data, study_site = TRUE){
    if(study_site == TRUE){
        for(i in 1:6) {
            lst_site[[i]] <- wilcox.test(x = data[[pairs_site[1, i]]],
                                         y = data[[pairs_site[2, i]]],
                                         exact = FALSE,
                                         conf.int = TRUE)[c(8)]
            
            lst_site[[i]] <- data_frame('Comparison' = pairs_names.site[[i]],
                                        Delta_CI.lower =
                                            round(lst_site[[i]]$conf.int[[1]], 2),
                                        Delta_CI.upper =
                                            round(lst_site[[i]]$conf.int[[2]], 2))
            out <- map_df(.x = lst_site,
                          ~ .x)
            }
    } else {
           lst_sex[[1]] <- wilcox.test(x = data[[pairs_sex[1, 1]]],
                                       y = data[[pairs_sex[2, 1]]],
                                       exact = FALSE,
                                       conf.int = TRUE)[c(8)]
            
           lst_sex[[1]] <- data_frame('Comparison' = pairs_names.sex[[1]],
                                      Delta_CI.lower =
                                          round(lst_sex[[1]]$conf.int[[1]], 2),
                                      Delta_CI.upper =
                                          round(lst_sex[[1]]$conf.int[[2]], 2))
            out <- map_df(.x = lst_sex,
                          ~ .x) 
        }
    out
}

# Define function for difference in proportions
prop_site <- function(data = data){
    data_vec <- data[['Study_site']]
    for(i in 1:6){
        x1 = length(!is.na(data_vec[data_vec ==  pairs_site[1, i]]))
        n1 = length(!is.na(data_vec[data_vec == pairs_site[1, i]])) +
            length(!is.na(data_vec[data_vec == pairs_site[2, i]]))
        x2 = length(!is.na(data_vec[data_vec == pairs_site[2, i]]))
        n2 = length(!is.na(data_vec[data_vec == pairs_site[1, i]])) +
            length(!is.na(data_vec[data_vec == pairs_site[2, i]]))
        lst_site[[i]] <- BinomDiffCI(x1 = x1,
                                     x2 = x2,
                                     n1 = n1,
                                     n2 = n2,
                                     method = 'ac')[2:3]
        lst_site[[i]] <- data_frame('Comparison' = pairs_names.site[[i]],
                                    n1 = x1,
                                    n2 = x2,
                                    Delta_CI.lower = round(lst_site[[i]][1], 2),
                                    Delta_CI.upper = round(lst_site[[i]][2], 2))
        out <- map_df(.x = lst_site,
                      ~ .x)
    }
    out
}

prop_sex <- function(data = data){
    data_vec <- data[['Sex']]
    x1 = length(!is.na(data_vec[data_vec ==  pairs_sex[1, 1]]))
    n1 = length(!is.na(data_vec[data_vec == pairs_sex[1, 1]])) +
        length(!is.na(data_vec[data_vec == pairs_sex[2, 1]]))
    x2 = length(!is.na(data_vec[data_vec == pairs_sex[2, 1]]))
    n2 = length(!is.na(data_vec[data_vec == pairs_sex[1, 1]])) +
        length(!is.na(data_vec[data_vec == pairs_sex[2, 1]]))
    lst_sex[[1]] <- BinomDiffCI(x1 = x1,
                                x2 = x2,
                                n1 = n1,
                                n2 = n2,
                                method = 'ac')[2:3]
    lst_sex[[1]] <- data_frame('Comparison' = pairs_names.sex[[1]],
                               n1 = x1,
                               n2 = x2,
                               Delta_CI.lower = round(lst_sex[[1]][1], 2),
                               Delta_CI.upper = round(lst_sex[[1]][2], 2))
    out <- map_df(.x = lst_sex,
                  ~ .x)
    out
}

test <- function(data, strata, study_site = TRUE){
    s <- enquo(strata)
    if(study_site == TRUE){
        foo <- data %>% 
            select(Study_site, !!s) %>% 
            filter(!is.na(!!s)) %>% 
            group_by(!!s) %>% 
            nest() %>% 
            arrange(!!s) %>% 
            mutate(output = map(.x = data,
                                ~ prop_site(.x))) %>% 
            mutate(filtered = map(.x = output,
                                  ~ .x %>% filter(n1 > 0 & n2 > 0)))
    } else {
        foo <- data %>% 
            select(Sex, !!s) %>% 
            filter(!is.na(!!s)) %>% 
            group_by(!!s) %>% 
            nest() %>% 
            arrange(!!s) %>% 
            mutate(output = map(.x = data,
                                ~ prop_sex(.x))) %>% 
            mutate(filtered = map(.x = output,
                                  ~ .x %>% filter(n1 > 0 & n2 > 0)))
    }
    foo
}

### TESTS ####
x <- test(data = demo, strata = Education)
walk(x$filtered, ~print(.x))

y <- test(data = demo, strata = Education, study_site = FALSE)
walk(y$filtered, ~print(.x))
```

----

# Demographic data

## Age

### Full cohort
```{r age_full}
data %>% 
    select(Age_years) %>% 
    summarise(n = n(),
              Mean = round(mean(Age_years, na.rm = TRUE), 1),
              SD = round(sd(Age_years, na.rm = TRUE), 1)) %>% 
    bind_cols(groupwiseMean(Age_years ~ 1,
                            data = data,
                            traditional = TRUE)) %>% 
                  select(1, 2, 3, 7:9) %>% 
    kable()

data %>% 
    ggplot(data = .) +
    aes(x = 'Full cohort',
        y = Age_years) +
    geom_boxplot() +
    labs(title = 'Age: full cohort',
         y = 'Years') +
    scale_y_continuous(limits = c(0, max(data$Age_years))) +
    theme(axis.title.x = element_blank())
```

### By sex
```{r age_sex}
# Table of descriptive statistics
data %>% 
    select(Age_years, Sex) %>% 
    group_by(Sex) %>% 
    summarise(n = n(),
              Mean = round(mean(Age_years, na.rm = TRUE), 1),
              SD = round(sd(Age_years, na.rm = TRUE), 1)) %>% 
    bind_cols(groupwiseMean(Age_years ~ Sex,
                            data = data,
                            boot = TRUE,
                            traditional = FALSE, 
                            bca = TRUE) %>% 
                  select(5:7)) %>%
    kable()

# Boxplot
data %>% 
    ggplot(data = .) +
    aes(x = Sex,
        y = Age_years) +
    geom_boxplot() +
    labs(title = 'Age: by sex',
         y = 'Years') +
    scale_y_continuous(limits = c(0, max(data$Age_years))) +
    theme(axis.title.x = element_blank())

# Table of 95% CI of the difference in means
data %>% 
    select(ID, Age_years, Sex) %>% 
    spread(key = Sex,
           value = Age_years) %>% 
    select(-ID) %>% 
    delta_mean(data = ., 
               study_site = FALSE) %>% 
    kable()
```

### By study site
```{r age_site}
# Table of descriptive statistics
data %>% 
    select(Age_years, Study_site) %>% 
    group_by(Study_site) %>% 
    summarise(n = n(),
              Mean = round(mean(Age_years, na.rm = TRUE), 1),
              SD = round(sd(Age_years, na.rm = TRUE), 1)) %>% 
    bind_cols(groupwiseMean(Age_years ~ Study_site,
                            data = data,
                            boot = TRUE,
                            traditional = FALSE, 
                            bca = TRUE) %>% 
                  select(5:7)) %>%
    kable()

# Boxplot
data %>% 
    ggplot(data = .) +
    aes(x = Study_site,
        y = Age_years) +
    geom_boxplot() +
    labs(title = 'Age by study site',
         subtitle = 'U: Urban, R: Rural',
         y = 'Years') +
    scale_y_continuous(limits = c(0, max(data$Age_years))) +
    theme(axis.title.x = element_blank())

# Table of 95% CI of the difference in means
data %>% 
    select(ID, Age_years, Study_site) %>% 
    spread(key = Study_site,
           value = Age_years) %>% 
    select(-ID) %>% 
    delta_mean(data = .) %>% 
    kable()
```

## Sex

### Full cohort
```{r sex_full}

```

# Tabular summaries

```{r skimr}
# Set various skimr defaults to NULL
skim_with(numeric = list(hist = NULL, p0 = NULL, p100 = NULL), 
          integer = list(hist = NULL, p0 = NULL, p100 = NULL),
          factor = list(ordered = NULL))
```

## Full cohort
```{r full}
data %>% 
    # Remove unnessesary columns
    select(-ID, -Study_site) %>% 
    # Summarise
    skim() 
```

## By sex
```{r sex}
data %>% 
    # Remove unnessesary columns
    select(-ID, -Study_site) %>% 
    # Group by sex
    group_by(Sex) %>% 
    # Summarise
    skim() 
```

## By study site
```{r site}
data %>% 
    # Remove unnessesary columns
    select(-ID) %>% 
    # Group by sex
    group_by(Study_site) %>% 
    # Summarise
    skim() 
```
----

# Session information

```{r session_info, echo = FALSE}
sessionInfo()
```